"""
(class) - Classes are templates for creating new objects.

Classes generate new objects (instances) that can have
their own attributes and methods.

Objects generated by the class can use their internal
data to perform various actions.

By convention, we use PascalCase for class names.

Every class is a template for general output according to arguments
informed.

Parameters: are the names given to the attributes that a function can
to receive. Define which arguments are accepted by a function,
may or may not have a default value.

Arguments: are the values that are actually passed to a
function.

# string = 'Luiz'  # str
# print(string.upper())
# print(isinstance(string, str))
"""
# !Example


class People:
    ...


p1 = People()
p1.name = 'Luiz'
p1.surname = 'Otávio'

p2 = People()
p2.name = 'Maria'
p2.surname = 'Joana'

print(p1.name)
print(p1.surname)

print(p2.name)
print(p2.surname)
