"""
Introduction to __init__ method (attribute initializer):

Classes generate new objects (instances) that can have
their own attributes and methods.

Objects generated by the class can use their internal
data to perform various actions.

By convention, we use PascalCase for class names.

string = 'Luiz'  # str
print(string.upper())
print(isinstance(string, str))
"""


class People:
    def __init__(self, name, surname):
        self.name = name
        self.surname = surname


p1 = People('Luiz', 'Otávio')  # -> p1 = self.name
# p1.name = 'Luiz'
# p1.surname = 'Otávio'

p2 = People('Maria', 'Joana')
# p2.name = 'Maria'
# p2.surname = 'Joana'

print(p1.name)
print(p1.surname)

print(p2.name)
print(p2.surname)
